package interfaz;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Automovil;
import logica.Controlador;

public class VerDatos extends javax.swing.JFrame {

    Controlador controlador = null;
    
    public VerDatos() {
        controlador = new Controlador();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAutomovil = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(197, 74, 131));
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/palm-150.png"))); // NOI18N
        header.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/sun-150.png"))); // NOI18N
        header.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lemon", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos");
        header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/mixed-drinks-130.png"))); // NOI18N
        header.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/confetti.png"))); // NOI18N
        header.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lemon", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ver");
        header.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 130));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAutomovil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblAutomovil.setFocusable(false);
        jScrollPane1.setViewportView(tblAutomovil);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 530, 380));

        btnEditar.setBackground(new java.awt.Color(0, 204, 255));
        btnEditar.setFont(new java.awt.Font("Lemon", 1, 24)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/edit-icon.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 102, 102), new java.awt.Color(51, 204, 255)));
        btnEditar.setFocusable(false);
        btnEditar.setIconTextGap(6);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 230, -1));

        btnActualizar.setBackground(new java.awt.Color(255, 102, 51));
        btnActualizar.setFont(new java.awt.Font("Lemon", 1, 24)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/recycle-icon.png"))); // NOI18N
        btnActualizar.setText("CARGAR");
        btnActualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 51, 0), new java.awt.Color(255, 153, 51)));
        btnActualizar.setFocusable(false);
        btnActualizar.setIconTextGap(6);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 230, -1));

        btnEliminar.setBackground(new java.awt.Color(237, 7, 121));
        btnEliminar.setFont(new java.awt.Font("Lemon", 1, 24)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/delete-icon.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 0, 102), new java.awt.Color(255, 102, 204)));
        btnEliminar.setFocusable(false);
        btnEliminar.setIconTextGap(6);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 230, -1));

        jLabel7.setFont(new java.awt.Font("Lemon", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Datos de Automóviles");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/neon-lights-950.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 910, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void cargarTabla() {
        
        // Realizamos la modificación respectiva para que ni las filas ni las columnas sean editables
            
       
        DefaultTableModel tabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            
        };
                
        // Cargamos los nombres de las columnas
        
        String[] tablaColumnas = {"N° Auto", "Modelo", "Marca", "Motor", "Color", "Patente", "N° Puertas"};

        tabla.setColumnIdentifiers(tablaColumnas);
        
        // Setteamos el modelo detabla que usará el panel tblAutomovil
        
        tblAutomovil.setModel(tabla);
        
        // Cargamos en una lista un ArrayList<> que tenga los registros con los cuales recorrer con for
        
        ArrayList<Automovil> listaAutomoviles = controlador.encontrarLosAutomoviles();
         
        // Rellenamos la tabla con los registros traídos de la BBDD
        
        // Que la tabla no esté vacía, es decir tenga más de 0 registros
        if (tblAutomovil.getColumnCount() > 0) {
            // Recorremos cada elemento de nuestra lista de automóviles
            for (Automovil auto : listaAutomoviles) {
                // Armamos un vector de tipo Object[], ya que los elementos del registro pueden ser de diferente tipo
                
                Object[] registro = {auto.getAutoId(), auto.getModelo(), auto.getMarca(), auto.getMotor(),
                auto.getColor(), auto.getPatente(), auto.getCantidadPuertas()};
                
                // A cada registro completo, lo asignamos en la tabla (no la tabla panel, la tabla en memoria)
                
                tabla.addRow(registro);
                
            }
        }
        
        
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        cargarTabla();
        
    }//GEN-LAST:event_formWindowOpened

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        EditarDatos editarDatos = new EditarDatos();
        editarDatos.setVisible(true);
        editarDatos.setLocationRelativeTo(null);
        

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        // Verificamos que la tabla (panel a la que está setteada) no se encuentre vacía 
        if (tblAutomovil.getRowCount() > 0) {
            
            // Verificamos que el elemento que seleccionemos EXISTA (-1 == no existe)
            if (tblAutomovil.getSelectedRow() != -1) {
                
                // Conseguimos el id del objeto registrado
                
                int numeroVehiculo = Integer.parseInt(String.valueOf(tblAutomovil.getValueAt(tblAutomovil.getSelectedRow(), 0)));
                
                // Configuramos las opciones para la eliminación del registro, con un vector de tipo Object[]
                
                Object[] opciones = {"Si", "No"};
                
                int resultadoOpcion = JOptionPane.showOptionDialog(
                null,
                "¿Está seguro de que desea borrar el automóvil seleccionado?",
                "Confirmación - Eliminación de Automóvil",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                opciones[0]
                );
                
                // Hacemos la validicación
                
                if (resultadoOpcion == JOptionPane.YES_OPTION) {
                    
                    // Le mandamos al controlador de la lógica el número obtenido para borrar
                    
                    Automovil vehiculoEncontrado = controlador.buscarAutomovil(numeroVehiculo);
                    
                    // Conseguimos el ID asociado del vehículo encontrado, hacemos todo estos pasos
                    // porque tenemos que corroborar que borremos el registro correcto y no lo que
                    // consigamos en la tabla, que es una representación gráfica
                    
                    int numeroAutomovilEncontrado = vehiculoEncontrado.getAutoId();
                    
                    // Mandamos un mensaje de eliminación antes de borrar
                    
                    JOptionPane.showMessageDialog(null, "Automóvil Eliminado: " + vehiculoEncontrado.toString());
                    
                    controlador.eliminarVehiculoSeleccionado(numeroAutomovilEncontrado);
                    
                    cargarTabla();
                    
                }
                
                
            } else {
                JOptionPane.showMessageDialog(null, "No se seleccionó ningún vehículo",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        cargarTabla();
        
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAutomovil;
    // End of variables declaration//GEN-END:variables
}
